services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    networks:
      - my_network

  django:
    build: Site
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./Site:/Site
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - .env.db
      - Site/.env.site
    ports:
      - "8000:8000"
    networks:
      - my_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 backend.wsgi"

  bot:
    build: ./TelegramBot
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.db
      - TelegramBot/.env.tg
    networks:
      - my_network
    command: [ "python", "main_olympiads.py" ]

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - django
    volumes:
      - ./nginx/certs:/etc/ssl/certs
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - my_network

  flower:
    image: mher/flower
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    networks:
      - my_network

  worker:
    restart: always
    build: ./Site
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - django
    env_file:
      - .env.db
    command: 'celery -A Site worker -l info'
    networks:
      - my_network

  beat:
    restart: always
    build: ./Site
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - django
      - worker
    env_file:
      - .env.db
    command: 'celery -A Site beat -l info'
    networks:
      - my_network


volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my_network:
