upstream django_server {
    server django:8000;
}

server {
    listen 80;
    server_name olympshub.ru www.olympshub.ru;

    # Перенаправляем все HTTP-запросы на HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name olympshub.ru www.olympshub.ru;

    ssl_certificate /etc/letsencrypt/live/olympshub.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/olympshub.ru/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    keepalive_timeout 70;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_stapling on;
    ssl_trusted_certificate /etc/letsencrypt/live/olympshub.ru/chain.pem;  # Опционально

    location / {
        proxy_pass http://django_server;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/app/web/staticfiles/;
    }

    location /media/ {
        alias /home/app/web/mediafiles/;
    }
}
